name: Build Lint Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_SECRETS }}" > .env

      - name: Build SvelteKit application
        run: bun run build

      - name: Install playwright browsers
        run: bun playwright install --with-deps

      - name: Lint SvelteKit application
        run: bun lint

      - name: Test SvelteKit application
        run: bun test:run
